-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\DualBoxcarAveragerFixedPoint\Positive_rsvd.vhd
-- Created: 2025-03-30 20:27:36
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Positive_rsvd
-- Source Path: DualBoxcarAveragerFixedPoint/DSP/Detect Rise Positive/Positive
-- Hierarchy Level: 2
-- Model version: 6.42
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Positive_rsvd IS
  PORT( u                                 :   IN    signed(16 DOWNTO 0);  -- sfix17
        y                                 :   OUT   std_logic
        );
END Positive_rsvd;


ARCHITECTURE rtl OF Positive_rsvd IS

  -- Signals
  SIGNAL Compare_relop1                   : std_logic;

BEGIN
  
  Compare_relop1 <= '1' WHEN u > to_signed(16#00000#, 17) ELSE
      '0';

  y <= Compare_relop1;

END rtl;

