-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\DualBoxcarAveragerFixedPoint\Single_Averager.vhd
-- Created: 2025-03-30 20:27:36
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Single_Averager
-- Source Path: DualBoxcarAveragerFixedPoint/DSP/Dual_Averager_0/Single_Averager
-- Hierarchy Level: 2
-- Model version: 6.42
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Single_Averager IS
  PORT( Clk                               :   IN    std_logic;
        Reset                             :   IN    std_logic;
        SignalInput                       :   IN    signed(15 DOWNTO 0);  -- int16
        Trigger                           :   IN    std_logic;
        TriggerDelay                      :   IN    unsigned(15 DOWNTO 0);  -- uint16
        GateLength                        :   IN    unsigned(15 DOWNTO 0);  -- uint16
        AvgLength                         :   IN    unsigned(15 DOWNTO 0);  -- uint16
        DataOut                           :   OUT   signed(47 DOWNTO 0);  -- sfix48
        AveragingFlag                     :   OUT   std_logic  -- ufix1
        );
END Single_Averager;


ARCHITECTURE rtl OF Single_Averager IS

  -- Component Declarations
  COMPONENT Boxcar_FixPt
    PORT( Clk                             :   IN    std_logic;
          Reset                           :   IN    std_logic;
          SignalInput                     :   IN    signed(15 DOWNTO 0);  -- int16
          Trigger                         :   IN    std_logic;
          TriggerDelay                    :   IN    unsigned(15 DOWNTO 0);  -- uint16
          GateLength                      :   IN    unsigned(15 DOWNTO 0);  -- uint16
          AverageOut                      :   OUT   signed(31 DOWNTO 0);  -- int32
          AveragingFlag                   :   OUT   std_logic;  -- ufix1
          DataValid                       :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT Averager_FixPt
    PORT( Clk                             :   IN    std_logic;
          Reset                           :   IN    std_logic;
          DataIn                          :   IN    signed(31 DOWNTO 0);  -- int32
          AvgLength                       :   IN    unsigned(15 DOWNTO 0);  -- uint16
          ValidIn                         :   IN    std_logic;  -- ufix1
          DataOut                         :   OUT   signed(47 DOWNTO 0)  -- sfix48
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Boxcar_FixPt
    USE ENTITY work.Boxcar_FixPt(rtl);

  FOR ALL : Averager_FixPt
    USE ENTITY work.Averager_FixPt(rtl);

  -- Signals
  SIGNAL AverageOut                       : signed(31 DOWNTO 0);  -- int32
  SIGNAL DataValid                        : std_logic;  -- ufix1

BEGIN
  u_Boxcar_FixPt : Boxcar_FixPt
    PORT MAP( Clk => Clk,
              Reset => Reset,
              SignalInput => SignalInput,  -- int16
              Trigger => Trigger,
              TriggerDelay => TriggerDelay,  -- uint16
              GateLength => GateLength,  -- uint16
              AverageOut => AverageOut,  -- int32
              AveragingFlag => AveragingFlag,  -- ufix1
              DataValid => DataValid  -- ufix1
              );

  u_Averager_FixPt : Averager_FixPt
    PORT MAP( Clk => Clk,
              Reset => Reset,
              DataIn => AverageOut,  -- int32
              AvgLength => AvgLength,  -- uint16
              ValidIn => DataValid,  -- ufix1
              DataOut => DataOut  -- sfix48
              );

END rtl;

