-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\System_Template\MATLAB_Function.vhd
-- Created: 2021-09-30 12:46:01
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: System_Template/DSP/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MATLAB_Function IS
  PORT( Clk                               :   IN    std_logic;
        Reset                             :   IN    std_logic;
        InputA                            :   IN    signed(15 DOWNTO 0);  -- int16
        OutputA                           :   OUT   unsigned(15 DOWNTO 0)  -- uint16
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Component Declarations
  COMPONENT MATLAB_Function_FixPt
    PORT( Clk                             :   IN    std_logic;
          Reset                           :   IN    std_logic;
          InputA                          :   IN    signed(15 DOWNTO 0);  -- int16
          OutputA                         :   OUT   unsigned(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MATLAB_Function_FixPt
    USE ENTITY work.MATLAB_Function_FixPt(rtl);

BEGIN
  -- This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  -- fixed-point.The variant subsystem contains two blocks:
  -- 1. MATLAB Function is the original code from the MATLAB function block. Modify this block to update your code or 
  -- resolve errors
  -- 
  -- 2. MATLAB Function_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  -- this block will be overwritten on the next conversion.
  -- 
  -- The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more.. 

  u_MATLAB_Function_FixPt : MATLAB_Function_FixPt
    PORT MAP( Clk => Clk,
              Reset => Reset,
              InputA => InputA,  -- int16
              OutputA => OutputA  -- uint16
              );

END rtl;

