--------------------------------------------------------------------------------
-- File: PulseStar_volo_shim.vhd
-- Generated: 2025-10-25 18:42:46
-- Generator: tools/generate_volo_app.py
--
-- ⚠️  GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
-- This file is automatically generated from the VoloApp model.
-- To modify, update PulseStar_app.yaml and regenerate.
--
-- Description:
--   Register mapping shim for PulseStar VoloApp.
--   Maps raw Control Registers (CR20-CR30) to friendly signal names
--   and instantiates the application main entity.
--
-- Layer 2 of 3-Layer VoloApp Architecture:
--   Layer 1: MCC_TOP_volo_loader.vhd (static, shared)
--   Layer 2: PulseStar_volo_shim.vhd (THIS FILE - generated)
--   Layer 3: PulseStar_volo_main.vhd (hand-written app logic)
--
-- Register Mapping:

--   CR20: Pulse Width → pulse_width : std_logic_vector(7 downto 0)

--   CR21: Duty Cycle → duty_cycle : std_logic_vector(6 downto 0)

--   CR22: Enable Output → enable_output : std_logic

--
-- References:
--   - docs/VOLO_APP_DESIGN.md
--   - PulseStar_app.yaml
--------------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

library WORK;
use WORK.volo_common_pkg.all;

entity PulseStar_volo_shim is
    port (
        ------------------------------------------------------------------------
        -- Clock and Reset
        ------------------------------------------------------------------------
        Clk         : in  std_logic;
        Reset       : in  std_logic;  -- Active-high reset

        ------------------------------------------------------------------------
        -- VOLO Control Signals (from MCC_TOP_volo_loader)
        ------------------------------------------------------------------------
        volo_ready  : in  std_logic;  -- CR0[31] - Set by loader
        user_enable : in  std_logic;  -- CR0[30] - User control
        clk_enable  : in  std_logic;  -- CR0[29] - Clock gating
        loader_done : in  std_logic;  -- BRAM loader FSM done signal

        ------------------------------------------------------------------------
        -- Application Registers (from MCC_TOP_volo_loader)
        -- Raw Control Registers CR20-CR30
        ------------------------------------------------------------------------

        app_reg_20 : in  std_logic_vector(31 downto 0);

        app_reg_21 : in  std_logic_vector(31 downto 0);

        app_reg_22 : in  std_logic_vector(31 downto 0);


        ------------------------------------------------------------------------
        -- BRAM Interface (from volo_bram_loader FSM)
        ------------------------------------------------------------------------
        bram_addr   : in  std_logic_vector(11 downto 0);  -- 4KB address space
        bram_data   : in  std_logic_vector(31 downto 0);  -- 32-bit data
        bram_we     : in  std_logic;                      -- Write enable

        ------------------------------------------------------------------------
        -- MCC I/O (from CustomWrapper)
        ------------------------------------------------------------------------
        InputA      : in  std_logic_vector(31 downto 0);
        InputB      : in  std_logic_vector(31 downto 0);
        OutputA     : out std_logic_vector(31 downto 0);
        OutputB     : out std_logic_vector(31 downto 0)
    );
end entity PulseStar_volo_shim;

architecture rtl of PulseStar_volo_shim is

    ----------------------------------------------------------------------------
    -- Friendly Signal Declarations (MCC-Agnostic Interface)
    ----------------------------------------------------------------------------

    signal pulse_width : std_logic_vector(7 downto 0);  -- Pulse duration in clock cycles (1-255)

    signal duty_cycle : std_logic_vector(6 downto 0);  -- PWM duty cycle percentage (0-100%)

    signal enable_output : std_logic;  -- Toggle pulse output on/off


    ----------------------------------------------------------------------------
    -- Global Enable Signal
    -- Combines all VOLO_READY control bits for safe operation
    ----------------------------------------------------------------------------
    signal global_enable : std_logic;

begin

    ----------------------------------------------------------------------------
    -- Global Enable Computation
    --
    -- All 4 conditions must be met for app to operate:
    --   1. volo_ready  = 1  (loader has deployed bitstream)
    --   2. user_enable = 1  (user has enabled module)
    --   3. clk_enable  = 1  (clock gating enabled)
    --   4. loader_done = 1  (BRAM loading complete)
    ----------------------------------------------------------------------------
    global_enable <= combine_volo_ready(volo_ready, user_enable, clk_enable, loader_done);

    ----------------------------------------------------------------------------
    -- Register Mapping: Control Registers → Friendly Signals
    --
    -- Extract appropriate bit ranges from raw Control Registers
    -- based on register type (COUNTER_8BIT, PERCENT, BUTTON)
    ----------------------------------------------------------------------------

    pulse_width <= app_reg_20(7 downto 0);  -- Pulse Width

    duty_cycle <= app_reg_21(6 downto 0);  -- Duty Cycle

    enable_output <= app_reg_22(0);  -- Enable Output


    ----------------------------------------------------------------------------
    -- Instantiate Application Main Entity
    --
    -- MCC-agnostic interface using friendly signal names only
    ----------------------------------------------------------------------------
    APP_MAIN_INST: entity WORK.PulseStar_volo_main
        port map (
            -- Standard Control Signals
            Clk     => Clk,
            Reset   => Reset,
            Enable  => global_enable,
            ClkEn   => clk_enable,

            -- Friendly Application Signals

            pulse_width => pulse_width,

            duty_cycle => duty_cycle,

            enable_output => enable_output,


            -- BRAM Interface (always exposed for consistency)
            bram_addr => bram_addr,
            bram_data => bram_data,
            bram_we   => bram_we,

            -- MCC I/O
            InputA  => InputA,
            InputB  => InputB,
            OutputA => OutputA,
            OutputB => OutputB
        );

end architecture rtl;